CREATE TABLE empresa (
	ID_EMPRESA INT auto_increment PRIMARY KEY,
    NOME_EMPRESA VARCHAR(45) NOT NULL,
    DATA_FUNDACAO DATE NOT NULL,
    NUMERO_FUNCIONARIOS INT NOT NULL,
    REGIAO_DO_BRASIL VARCHAR(10) NOT NULL,
    SETOR_DE_ATUACAO VARCHAR(10) NOT NULL
);